---
title: Linux CLI
---

## Prerequisites

Just like with anything we have to walk before we can run.

## Learning the Linux CLI

A thorough treatment of Linux CLI fundamentals geared towards the
beginner/novice is outside of the scope of this book. This book assumes some
familiarity with Linux and basic Linux CLI proficiency. That's not to say that
you _couldn't_ still work through this book and pass the [RHCSA][rhcsa] exam,
but be forwarned the learning curve is steep. But, I can thoroughly endorse any
of the following resources to help you get up to speed:

1. [Learning the Shell][learning-the-shell] from **LinuxCommand.org** and
  [The Linux Command Line][linux-command-line] by William Shotts

::: {.callout-tip}
This is my #1 go-to recommendation for beginners that want to learn
Linux and the Linux CLI. This is where I first learned Linux and the Linux CLI
many years ago.
:::

2. [Command Line Crash Course][command-line-crash-course] from **Learn Python
  the Hard Way** by Zed Shaw
3. MIT **Missing Semester** Series: [Introduction to the
  Shell][missing-semester-shell] & [Command-line
  Environment][missing-semester-command-line]

Becoming proficient in the Linux CLI is a pre-requisite to learning RHEL and
preparing for the [RHCSA][rhcsa] exam. If this is you, definitely check out the
resources above. It's probably only a few days or weeks of effort to get up to
speed on the basics. Then come back and work through the rest of this book.

[rhcsa]: ../appendices/glossary.qmd
[learning-the-shell]: https://www.linuxcommand.org/lc3_learning_the_shell.php
[linux-command-line]: https://www.linuxcommand.org/tlcl.php
[command-line-crash-course]: https://learnpythonthehardway.org/book/appendixa.html
[missing-semester-shell]: https://missing.csail.mit.edu/2026/course-shell/
[missing-semester-command-line]: https://missing.csail.mit.edu/2026/command-line-environment/

### Other notable mentions

There are some other free Linux learning resources worth mentioning. Some of
these are other projects I'm involved with.

4. [Linux Upskill Challenge][linux-upskill-challenge] I've contributed to this
  project as an editor
5. The [Linux Administration Course][linux-administration-course] written by
  Scott Champine (het_tanis) and maintained by the [ProLUG][prolug] community
  (I'm a _ProLUG Engineer_, come say "Hi" in the [Discord][prolug-discord]!)
6. [Linux Commands for Beginners][linux-commands-for-beginners] YouTube Playlist
  by [LearnLinuxTV][learn-linux-tv]

[linux-upskill-challenge]: https://linuxupskillchallenge.org/
[linux-administration-course]: https://professionallinuxusersgroup.github.io/lac/syllabus.html
[prolug]: https://prolug.org/
[prolug-discord]: https://discord.com/invite/m6VPPD9usw
[linux-commands-for-beginners]: https://youtube.com/playlist?list=PLT98CRl2KxKHaKA9-4_I38sLzK134p4GJ&si=fhFuZX3oHMk0puAO
[learn-linux-tv]: https://www.youtube.com/@LearnLinuxTV
