project:
  type: book

book:
  # Working title
  title: "The RHCSA Field Manual"
  subtitle: "A hands-on guide to Red Hat Enterprise Linux 10 and the EX200 exam"
  author: "Alex Kraker"
  date: "5/12/2026"
  repo-url: https://github.com/kraker/rhcsa-field-manual
  repo-branch: main
  repo-subdir: book
  repo-actions: [issue, source]
  chapters:
    - index.qmd
    - part: "Front Matter"
      chapters:
        - 00-preface.qmd
        - 01-acknowledge.qmd
    - part: "Prerequisites"
      chapters:
        - prereqs/00-linux-cli.qmd
        - prereqs/01-redhat-account.qmd
        - prereqs/02-rhcsa-exam.qmd
        - prereqs/03-linux-workstation.qmd
        - prereqs/04-vagrant-lab.qmd

    # - part: "Prerequisites"
    #   chapters:
    #     - prereqs/00-linux-cli.qmd
    #     - prereqs/01-lab-setup.qmd
    # - part: "Chapters"
    #   chapters:
        # - chapters/01-exam-overview.qmd
        # - chapters/02-installation.qmd
        # - chapters/03-file-management.qmd
        # - chapters/04-users-groups.qmd
        # - chapters/05-shell-scripting.qmd
        # - chapters/06-permissions.qmd
        # - chapters/07-processes-services.qmd
        # - chapters/08-package-management.qmd
        # - chapters/09-storage-lvm.qmd
        # - chapters/10-networking.qmd
        # - chapters/11-selinux.qmd
        # - chapters/12-firewall.qmd
        # - chapters/13-boot-grub.qmd
        # - chapters/14-logging.qmd
        # - chapters/15-scheduled-tasks.qmd
        # - chapters/16-flatpak.qmd
        # - chapters/17-troubleshooting.qmd
    - part: "Practice Exams"
      chapters:
        - practice/00-practice-exam-1.qmd
        - practice/01-practice-exam-2.qmd
  appendices:
    - appendices/00-windows-workstation.qmd
    - appendices/01-command-reference.qmd
    - appendices/02-glossary.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-expand: true
    theme:
      dark: cyborg
      light: yeti
  # pdf:
  #   documentclass: scrreprt

execute:
  # re-execute a document only when its source file changes.
  freeze: auto

knitr:
  opts_knit:
    # Default to $HOME for executable {bash} code-blocks
    root.dir: "~"
